name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Run lint check
      - run: npx nx affected -t lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Run lint check
      - run: npx nx affected -t test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3
      
      # Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Run lint check
      - run: npx nx affected -t build
